// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc841.Odyssey;

import org.usfirst.frc841.Odyssey.commands.*;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.buttons.JoystickButton;

import org.usfirst.frc841.Odyssey.subsystems.*;


/**
 * This class is the glue that binds the controls on the physical operator
 * interface to the commands and command groups that allow control of the robot.
 */
public class OI {
    //// CREATING BUTTONS
    // One type of button is a joystick button which is any button on a joystick.
    // You create one by telling it which joystick it's on and which button
    // number it is.
    // Joystick stick = new Joystick(port);
    // Button button = new JoystickButton(stick, buttonNumber);

    // There are a few additional built in buttons you can use. Additionally,
    // by subclassing Button you can create custom triggers and bind those to
    // commands the same as any other Button.

    //// TRIGGERING COMMANDS WITH BUTTONS
    // Once you have a button, it's trivial to bind it to a button in one of
    // three ways:

    // Start the command when the button is pressed and let it run the command
    // until it is finished as determined by it's isFinished method.
    // button.whenPressed(new ExampleCommand());

    // Run the command while the button is being held down and interrupt it once
    // the button is released.
    // button.whileHeld(new ExampleCommand());

    // Start the command when the button is released  and let it run the command
    // until it is finished as determined by it's isFinished method.
    // button.whenReleased(new ExampleCommand());


    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public JoystickButton quickTurn;
    public JoystickButton stopQuickTurn;
    public Joystick driver;
    public JoystickButton openGrabber6;
    public JoystickButton closeGrabber5;
    public JoystickButton outArmBrace8;
    public JoystickButton inArmBrace7;
    public JoystickButton succBall;
    public JoystickButton spootBall;
    public JoystickButton hatchFrontEnable;
    public JoystickButton hatchFrontDisable;
    public JoystickButton hatchBackEnable;
    public JoystickButton hatchBackDisable;
    public JoystickButton elevatorUpEnable;
    public JoystickButton elevatorUpDisable;
    public JoystickButton elevatorDownEnable;
    public JoystickButton elevatorDownDisable;
    public Joystick coDriver;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public OI() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

        coDriver = new Joystick(1);
        
        elevatorDownDisable = new JoystickButton(coDriver, 7);
        elevatorDownDisable.whenReleased(new elevatorStop());
        elevatorDownEnable = new JoystickButton(coDriver, 7);
        elevatorDownEnable.whenPressed(new elevatorDown());
        elevatorUpDisable = new JoystickButton(coDriver, 8);
        elevatorUpDisable.whenReleased(new elevatorStop());
        elevatorUpEnable = new JoystickButton(coDriver, 8);
        elevatorUpEnable.whenPressed(new elevatorUp());
        hatchBackDisable = new JoystickButton(coDriver, 1);
        hatchBackDisable.whenReleased(new elbowStop());
        hatchBackEnable = new JoystickButton(coDriver, 1);
        hatchBackEnable.whenPressed(new elbowDown());
        hatchFrontDisable = new JoystickButton(coDriver, 2);
        hatchFrontDisable.whenReleased(new elbowStop());
        hatchFrontEnable = new JoystickButton(coDriver, 2);
        hatchFrontEnable.whenPressed(new elbowUp());
        spootBall = new JoystickButton(coDriver, 4);
        spootBall.whenPressed(new releaseCargo());
        succBall = new JoystickButton(coDriver, 3);
        succBall.whenPressed(new intakeCargo());
        inArmBrace7 = new JoystickButton(coDriver, 7);
        inArmBrace7.whenPressed(new SetArmBrace(false));
        outArmBrace8 = new JoystickButton(coDriver, 8);
        outArmBrace8.whenPressed(new SetArmBrace(true));
        closeGrabber5 = new JoystickButton(coDriver, 5);
        closeGrabber5.whenPressed(new SetGrabber(true)); 
        openGrabber6 = new JoystickButton(coDriver, 6);
        openGrabber6.whenPressed(new SetGrabber(false));
        driver = new Joystick(0);
        
        stopQuickTurn = new JoystickButton(driver, 6);
        stopQuickTurn.whenReleased(new StopQuickTurn());
        quickTurn = new JoystickButton(driver, 6);
        quickTurn.whenPressed(new QuickTurn());


        // SmartDashboard Buttons
        SmartDashboard.putData("Autonomous Command", new AutonomousCommand());
        SmartDashboard.putData("Drive", new Drive());
        SmartDashboard.putData("QuickTurn", new QuickTurn());
        SmartDashboard.putData("StopQuickTurn", new StopQuickTurn());
        SmartDashboard.putData("SetHatchElbow: Front", new SetHatchElbow(4000));
        SmartDashboard.putData("SetHatchElbow: Middle", new SetHatchElbow(2838));
        SmartDashboard.putData("SetGrabber: open", new SetGrabber(false));
        SmartDashboard.putData("SetGrabber: close", new SetGrabber(true));
        SmartDashboard.putData("SetArmBrace: out", new SetArmBrace(true));
        SmartDashboard.putData("SetArmBrace: in", new SetArmBrace(false));
        SmartDashboard.putData("Release", new Release());
        SmartDashboard.putData("SetElevatorHeight: low", new SetElevatorHeight(0));
        SmartDashboard.putData("SetElevatorHeight: high", new SetElevatorHeight(0));
        SmartDashboard.putData("cargoSTOP", new cargoSTOP());
        SmartDashboard.putData("releaseCargo", new releaseCargo());
        SmartDashboard.putData("intakeCargo", new intakeCargo());
        SmartDashboard.putData("elbowUp", new elbowUp());
        SmartDashboard.putData("elbowDown", new elbowDown());
        SmartDashboard.putData("elbowStop", new elbowStop());
        SmartDashboard.putData("elevatorUp", new elevatorUp());
        SmartDashboard.putData("elevatorDown", new elevatorDown());
        SmartDashboard.putData("elevatorStop", new elevatorStop());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
    public Joystick getdriver() {
        return driver;
    }

    public Joystick getcoDriver() {
        return coDriver;
    }


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS

    public Joystick getDriver() {
        return driver;
    }

    public Joystick getCoDriver() {
        return coDriver;
    }
}

